name: Forever
on:
  pull_request:
    types:
      [
        opened,
        synchronize,
        reopened,
        ready_for_review,
        edited,
        labeled,
        milestoned,
      ]
jobs:
  forever:
    runs-on: ubuntu-latest
    steps:
      - name: Randomly fail
        run: |
          while true; do
            echo "Running..."
            sleep 1
          done

