name: All checks pass
on:
  pull_request:
    types:
      [
        opened,
        synchronize,
        reopened,
        ready_for_review,
        edited,
        labeled,
        milestoned,
      ]
  check_run:
    types: [requested]
jobs:
  allchecks:
    runs-on: ubuntu-latest
    permissions:
      checks: read
      contents: read
    steps:
      - uses: wechuli/allcheckspassed@v1
        with:
          checks_exclude: "pr-title-check"
