name: Checks
on:
  pull_request:
    types:
      [
        opened,
        synchronize,
        reopened,
        ready_for_review,
        edited,
        labeled,
        milestoned,
      ]
jobs:
  job-fail:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Title
        uses: amannn/action-semantic-pull-request@47b15d52c5c30e94a17ec87eb8dd51ff5221fed9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            deps
            chore
            docs
            feat
            fix
            test
          requireScope: false
          subjectPattern: ^([A-Z].*[^.]|bump .*)$
