name: Checks
on:
  pull_request:
    types:
      [
        opened,
        synchronize,
        reopened,
        ready_for_review,
        edited,
        labeled,
        milestoned,
      ]
jobs:
  job-fail:
    runs-on: ubuntu-latest
    steps:
      - name: Randomly fail
        run: |
          if [ $((RANDOM % 2)) -eq 0 ]; then
              echo "Success"
              exit 0
          else
              echo "Failure"
              exit 1
          fi
